// Generated by tool/icon_font/build_icon_font.py from tool/icon_font/icons.txt. Do not edit.
//
// Glyphs from Phosphor Icons (https://phosphoricons.com), MIT licensed:
// see assets/fonts/LICENSE-phosphor.txt.

import 'package:flutter/widgets.dart';

/// The example's icon font: [IconData] Veneer draws natively with CoreText
/// (`NativeIcon.icon(AppIcons.plus)`) and Flutter draws with `Icon` in the
/// fallback UI.
abstract final class AppIcons {
  /// Phosphor `caret-left` (regular).
  static const IconData caretLeft = IconData(0xE000, fontFamily: 'AppIcons');

  /// Phosphor `x` (regular).
  static const IconData close = IconData(0xE001, fontFamily: 'AppIcons');

  /// Phosphor `dots-three` (regular).
  static const IconData dotsThree = IconData(0xE002, fontFamily: 'AppIcons');

  /// Phosphor `note-pencil` (regular).
  static const IconData notePencil = IconData(0xE003, fontFamily: 'AppIcons');

  /// Phosphor `sliders-horizontal` (regular).
  static const IconData slidersHorizontal = IconData(0xE004, fontFamily: 'AppIcons');

  /// Phosphor `export` (regular).
  static const IconData share = IconData(0xE005, fontFamily: 'AppIcons');

  /// Phosphor `check` (regular).
  static const IconData check = IconData(0xE006, fontFamily: 'AppIcons');

  /// Phosphor `lock` (fill).
  static const IconData lockFill = IconData(0xE007, fontFamily: 'AppIcons');

  /// Phosphor `headphones` (regular).
  static const IconData headphones = IconData(0xE008, fontFamily: 'AppIcons');

  /// Phosphor `chats-circle` (regular).
  static const IconData chatsCircle = IconData(0xE009, fontFamily: 'AppIcons');

  /// Phosphor `chats-circle` (fill).
  static const IconData chatsCircleFill = IconData(0xE00A, fontFamily: 'AppIcons');

  /// Phosphor `drop` (regular).
  static const IconData drop = IconData(0xE00B, fontFamily: 'AppIcons');

  /// Phosphor `drop` (fill).
  static const IconData dropFill = IconData(0xE00C, fontFamily: 'AppIcons');

  /// Phosphor `scissors` (regular).
  static const IconData scissors = IconData(0xE00D, fontFamily: 'AppIcons');

  /// Phosphor `gauge` (regular).
  static const IconData gauge = IconData(0xE00E, fontFamily: 'AppIcons');

  /// Phosphor `plus` (regular).
  static const IconData plus = IconData(0xE00F, fontFamily: 'AppIcons');

  /// Phosphor `microphone` (regular).
  static const IconData microphone = IconData(0xE010, fontFamily: 'AppIcons');

  /// Phosphor `microphone-slash` (regular).
  static const IconData microphoneSlash = IconData(0xE011, fontFamily: 'AppIcons');

  /// Phosphor `waveform` (regular).
  static const IconData waveform = IconData(0xE012, fontFamily: 'AppIcons');

  /// Phosphor `paper-plane-tilt` (fill).
  static const IconData paperPlaneTiltFill = IconData(0xE013, fontFamily: 'AppIcons');

  /// Phosphor `text-aa` (regular).
  static const IconData textAa = IconData(0xE014, fontFamily: 'AppIcons');

  /// Phosphor `smiley` (regular).
  static const IconData smiley = IconData(0xE015, fontFamily: 'AppIcons');

  /// Phosphor `at` (regular).
  static const IconData at = IconData(0xE016, fontFamily: 'AppIcons');

  /// Phosphor `images` (regular).
  static const IconData images = IconData(0xE017, fontFamily: 'AppIcons');

  /// Phosphor `camera` (regular).
  static const IconData camera = IconData(0xE018, fontFamily: 'AppIcons');

  /// Phosphor `file-text` (regular).
  static const IconData fileText = IconData(0xE019, fontFamily: 'AppIcons');

  /// Phosphor `file-text` (fill).
  static const IconData fileTextFill = IconData(0xE01A, fontFamily: 'AppIcons');

  /// Phosphor `pencil-simple` (regular).
  static const IconData pencilSimple = IconData(0xE01B, fontFamily: 'AppIcons');

  /// Phosphor `trash` (regular).
  static const IconData trash = IconData(0xE01C, fontFamily: 'AppIcons');

  /// Phosphor `sparkle` (regular).
  static const IconData sparkle = IconData(0xE01D, fontFamily: 'AppIcons');

  /// Phosphor `sparkle` (fill).
  static const IconData sparkleFill = IconData(0xE01E, fontFamily: 'AppIcons');

  /// Phosphor `copy` (regular).
  static const IconData copy = IconData(0xE01F, fontFamily: 'AppIcons');

  /// Phosphor `thumbs-up` (regular).
  static const IconData thumbsUp = IconData(0xE020, fontFamily: 'AppIcons');

  /// Phosphor `thumbs-down` (regular).
  static const IconData thumbsDown = IconData(0xE021, fontFamily: 'AppIcons');

  /// Phosphor `speaker-high` (regular).
  static const IconData speakerHigh = IconData(0xE022, fontFamily: 'AppIcons');

  /// Phosphor `heart` (fill).
  static const IconData heartFill = IconData(0xE023, fontFamily: 'AppIcons');

  /// Phosphor `lightning` (fill).
  static const IconData lightningFill = IconData(0xE024, fontFamily: 'AppIcons');

  /// Phosphor `tag` (fill).
  static const IconData tagFill = IconData(0xE025, fontFamily: 'AppIcons');

  /// Phosphor `circle-half` (regular).
  static const IconData circleHalf = IconData(0xE026, fontFamily: 'AppIcons');

  /// Phosphor `hand-grabbing` (regular).
  static const IconData handGrabbing = IconData(0xE027, fontFamily: 'AppIcons');

  /// Phosphor `squares-four` (regular).
  static const IconData squaresFour = IconData(0xE028, fontFamily: 'AppIcons');

  /// Phosphor `arrows-left-right` (regular).
  static const IconData arrowsLeftRight = IconData(0xE029, fontFamily: 'AppIcons');

  /// Phosphor `stack` (regular).
  static const IconData stack = IconData(0xE02A, fontFamily: 'AppIcons');

  /// Phosphor `stack` (fill).
  static const IconData stackFill = IconData(0xE02B, fontFamily: 'AppIcons');

  /// Phosphor `rocket-launch` (regular).
  static const IconData rocketLaunch = IconData(0xE02C, fontFamily: 'AppIcons');

  /// Phosphor `arrow-right` (regular).
  static const IconData arrowRight = IconData(0xE02D, fontFamily: 'AppIcons');

  /// Phosphor `play` (fill).
  static const IconData playFill = IconData(0xE02E, fontFamily: 'AppIcons');

  /// Phosphor `pause` (fill).
  static const IconData pauseFill = IconData(0xE02F, fontFamily: 'AppIcons');

  /// Phosphor `ruler` (regular).
  static const IconData ruler = IconData(0xE030, fontFamily: 'AppIcons');

  /// Phosphor `arrows-down-up` (regular).
  static const IconData arrowsDownUp = IconData(0xE031, fontFamily: 'AppIcons');

  /// Phosphor `circle` (fill).
  static const IconData circleFill = IconData(0xE032, fontFamily: 'AppIcons');
}
