#!/usr/bin/env python3
"""Builds the example's icon font from Phosphor Icons SVGs.

    pip install fonttools
    npm pack @phosphor-icons/core && tar xzf phosphor-icons-core-*.tgz
    python3 tool/icon_font/build_icon_font.py package/assets

Writes assets/fonts/AppIcons.ttf and lib/app_icons.dart (run from example/).
The font is a regular TrueType icon font: each SVG becomes one glyph in the
Private Use Area, on a 1024-unit em with the ascent at the top of the 256 pt
SVG viewBox and the descent at 0, so Flutter's `Icon` and Veneer's native
renderer both lay a glyph out exactly in its icon box.
"""

import re
import sys
from pathlib import Path

from fontTools.fontBuilder import FontBuilder
from fontTools.pens.cu2quPen import Cu2QuPen
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.ttGlyphPen import TTGlyphPen
from fontTools.svgLib.path import SVGPath

FAMILY = "AppIcons"
UPM = 1024
VIEWBOX = 256
FIRST_CODEPOINT = 0xE000
HERE = Path(__file__).resolve().parent
EXAMPLE = HERE.parent.parent


def camel(name: str) -> str:
    head, *rest = name.split("-")
    return head + "".join(part.capitalize() for part in rest)


def read_list():
    for line in (HERE / "icons.txt").read_text().splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        spec, *alias = line.split()
        name, _, weight = spec.partition(":")
        weight = weight or "regular"
        dart = alias[0] if alias else camel(name) + ("Fill" if weight == "fill" else "")
        yield name, weight, dart


def glyph_for(svg_path: Path):
    pen = TTGlyphPen(None)
    scale = UPM / VIEWBOX
    # SVG is y-down from the top; fonts are y-up from the baseline.
    target = TransformPen(Cu2QuPen(pen, max_err=1, reverse_direction=True), (scale, 0, 0, -scale, 0, UPM))
    SVGPath.fromstring(svg_path.read_bytes()).draw(target)
    return pen.glyph()


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    assets = Path(sys.argv[1])
    icons = list(read_list())
    dart_names = [d for _, _, d in icons]
    if len(set(dart_names)) != len(dart_names):
        sys.exit("duplicate Dart names in icons.txt")

    order = [".notdef"]
    glyphs = {".notdef": TTGlyphPen(None).glyph()}
    cmap = {}
    for i, (name, weight, dart) in enumerate(icons):
        svg = assets / weight / (f"{name}.svg" if weight == "regular" else f"{name}-{weight}.svg")
        if not svg.exists():
            sys.exit(f"missing {svg}")
        glyph_name = f"{name}-{weight}"
        order.append(glyph_name)
        glyphs[glyph_name] = glyph_for(svg)
        cmap[FIRST_CODEPOINT + i] = glyph_name

    fb = FontBuilder(UPM, isTTF=True)
    fb.setupGlyphOrder(order)
    fb.setupCharacterMap(cmap)
    fb.setupGlyf(glyphs)
    # The left side bearing must equal each glyph's xMin: rasterizers place
    # the outline from it, so a wrong value shifts the icon sideways.
    glyf = fb.font["glyf"]
    fb.setupHorizontalMetrics(
        {g: (UPM if g != ".notdef" else 0, getattr(glyf[g], "xMin", 0)) for g in order}
    )
    fb.setupHorizontalHeader(ascent=UPM, descent=0)
    fb.setupNameTable({"familyName": FAMILY, "styleName": "Regular"})
    fb.setupOS2(sTypoAscender=UPM, sTypoDescender=0, sTypoLineGap=0, usWinAscent=UPM, usWinDescent=0)
    fb.setupPost()
    font_out = EXAMPLE / "assets" / "fonts" / f"{FAMILY}.ttf"
    fb.save(str(font_out))

    lines = [
        "// Generated by tool/icon_font/build_icon_font.py from tool/icon_font/icons.txt. Do not edit.",
        "//",
        "// Glyphs from Phosphor Icons (https://phosphoricons.com), MIT licensed:",
        "// see assets/fonts/LICENSE-phosphor.txt.",
        "",
        "import 'package:flutter/widgets.dart';",
        "",
        "/// The example's icon font: [IconData] Veneer draws natively with CoreText",
        "/// (`NativeIcon.icon(AppIcons.plus)`) and Flutter draws with `Icon` in the",
        "/// fallback UI.",
        "abstract final class AppIcons {",
    ]
    for i, (name, weight, dart) in enumerate(icons):
        lines.append(f"  /// Phosphor `{name}` ({weight}).")
        lines.append(f"  static const IconData {dart} = IconData(0x{FIRST_CODEPOINT + i:X}, fontFamily: '{FAMILY}');")
    lines.append("}")
    dart_out = EXAMPLE / "lib" / "app_icons.dart"
    dart_out.write_text("\n".join(lines) + "\n")
    print(f"{len(icons)} icons -> {font_out.relative_to(EXAMPLE)} ({font_out.stat().st_size} bytes), {dart_out.relative_to(EXAMPLE)}")


if __name__ == "__main__":
    main()
